In [1]:
import pymysql
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
# Read the dataset into a dataframe
df = pd.read_csv('.\\ny_data.csv')

In [3]:
df.head()

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,RECORD DATE,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
0,50045746,SILVER RICE,Brooklyn,575A,FLATBUSH AVENUE,11225.0,3477899874,Japanese,1/25/2019,Violations were cited in the following area(s).,...,3/6/2022,Cycle Inspection / Re-inspection,40.659624,-73.960559,309.0,40.0,79801.0,3114847.0,3.050310e+09,BK60
1,41269825,EL QUINTO PINO,Manhattan,401,WEST 24 STREET,10011.0,2122066900,Latin American,10/26/2018,Violations were cited in the following area(s).,...,3/6/2022,Cycle Inspection / Re-inspection,40.747328,-74.001270,104.0,3.0,9300.0,1012799.0,1.007220e+09,MN13
2,50087061,EARNEST TEA CAFE,Brooklyn,6008,8 AVENUE,11220.0,3474575888,Coffee/Tea,12/9/2019,Establishment Closed by DOHMH. Violations were...,...,3/6/2022,Cycle Inspection / Initial Inspection,40.635372,-74.009692,307.0,38.0,11800.0,3143608.0,3.057850e+09,BK34
3,50037410,WINGSTOP,Manhattan,63,WEST 125 STREET,10027.0,2129879464,Chicken,12/9/2019,Establishment Closed by DOHMH. Violations were...,...,3/6/2022,Cycle Inspection / Compliance Inspection,40.807332,-73.944432,110.0,9.0,20000.0,1053498.0,1.017230e+09,MN11
4,41449659,POPEYES,Brooklyn,4930,KINGS HIGHWAY,11234.0,7184844754,Chicken,12/4/2017,Violations were cited in the following area(s).,...,3/6/2022,Calorie Posting / Initial Inspection,40.633516,-73.929089,318.0,45.0,72400.0,3213512.0,3.077330e+09,BK58

Let's check if there are any duplicate records.

Some attribute names need to be modified.

***

In [4]:
df[df.duplicated()==True]

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,RECORD DATE,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
19,41395881,THE VIG BAR,Manhattan,12,SPRING STREET,10012.0,2126250011,American,1/25/2018,Violations were cited in the following area(s).,...,3/6/2022,Cycle Inspection / Re-inspection,40.721242,-73.994581,102.0,1.0,4100.0,1007137.0,1.004780e+09,MN24
30,41580023,SAGE,Brooklyn,299301,GRAHAM AVENUE,NaN,7182186644,Thai,11/30/2019,Violations were cited in the following area(s).,...,3/6/2022,Cycle Inspection / Re-inspection,0.000000,0.000000,NaN,NaN,NaN,NaN,3.000000e+00,NaN
43,50043998,THE STATION CRAFT CUISINE,Queens,2507,QUEENS PLZ N,11101.0,7187861111,American,6/3/2019,Violations were cited in the following area(s).,...,3/6/2022,Cycle Inspection / Re-inspection,40.750812,-73.939906,401.0,26.0,3300.0,4005006.0,4.004150e+09,QN68
44,50043998,THE STATION CRAFT CUISINE,Queens,2507,QUEENS PLZ N,11101.0,7187861111,American,6/3/2019,Violations were cited in the following area(s).,...,3/6/2022,Cycle Inspection / Re-inspection,40.750812,-73.939906,401.0,26.0,3300.0,4005006.0,4.004150e+09,QN68
50,50011610,BIG DADDY'S PIZZA,Brooklyn,68,LORRAINE STREET,11231.0,7187979100,Pizza,6/29/2016,Violations were cited in the following area(s).,...,3/6/2022,Cycle Inspection / Initial Inspection,40.674441,-74.007109,306.0,38.0,5300.0,3008668.0,3.005800e+09,BK33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341465,41206524,CHOICE MARKET,Brooklyn,318,LAFAYETTE AVENUE,11238.0,7182305234,American,8/18/2021,Violations were cited in the following area(s).,...,3/6/2022,Cycle Inspection / Initial Inspection,40.688505,-73.963130,302.0,35.0,19700.0,3055550.0,3.019470e+09,BK69
341493,50054846,EONS,Queens,6142,188TH ST,11365.0,7184874807,Greek,1/30/2020,Violations were cited in the following area(s).,...,3/6/2022,Cycle Inspection / Re-inspection,40.739238,-73.786184,408.0,23.0,134700.0,4439482.0,4.070750e+09,QN41
341494,50054846,EONS,Queens,6142,188TH ST,11365.0,7184874807,Greek,1/30/2020,Violations were cited in the following area(s).,...,3/6/2022,Cycle Inspection / Re-inspection,40.739238,-73.786184,408.0,23.0,134700.0,4439482.0,4.070750e+09,QN41
341570,50059901,NEW YORK STOCK EXCHANGE EXECUTIVE SERVICES,Manhattan,11,WALL STREET,10005.0,2126563815,American,5/11/2018,Violations were cited in the following area(s).,...,3/6/2022,Cycle Inspection / Initial Inspection,40.707392,-74.011106,101.0,1.0,700.0,1078982.0,1.000230e+09,MN25
341620,50085357,MEMO SHISH KEBAB,Manhattan,100,WEST 23 STREET,10011.0,2123812115,Turkish,9/9/2021,Violations were cited in the following area(s).,...,3/6/2022,Cycle Inspection / Initial Inspection,40.743074,-73.993237,104.0,3.0,9100.0,1014803.0,1.007980e+09,MN13

In [5]:
df = df.drop_duplicates()

In [6]:
restaurant = df[['CAMIS', 'DBA', 'BUILDING', 'STREET', 'BORO', 'ZIPCODE', 'PHONE', 'CUISINE DESCRIPTION']]

In [7]:
print(restaurant)

           CAMIS                         DBA BUILDING                STREET  \
0       50045746                 SILVER RICE     575A       FLATBUSH AVENUE
1       41269825              EL QUINTO PINO      401      WEST   24 STREET
2       50087061            EARNEST TEA CAFE     6008              8 AVENUE
3       50037410                    WINGSTOP       63      WEST  125 STREET
4       41449659                     POPEYES     4930         KINGS HIGHWAY
...          ...                         ...      ...                   ...
341621  41477814  2 BROS PIZZA, CORVO COFFEE      542              9 AVENUE
341622  50001948              BLOOM'S TAVERN      208      EAST   58 STREET
341623  41290515    MI BELLA DAMA RESTAURANT      296  KNICKERBOCKER AVENUE
341624  41377321        DEILINE'S RESTAURANT     1544      EAST  174 STREET
341625  50041455                      DUNKIN      322     LIVINGSTON STREET

             BORO  ZIPCODE       PHONE CUISINE DESCRIPTION
0        Brooklyn  11225.0  3477899874            Japanese
1       Manhattan  10011.0  2122066900      Latin American
2        Brooklyn  11220.0  3474575888          Coffee/Tea
3       Manhattan  10027.0  2129879464             Chicken
4        Brooklyn  11234.0  7184844754             Chicken
...           ...      ...         ...                 ...
341621  Manhattan  10018.0  2126952642               Pizza
341622  Manhattan  10022.0  2123089400            American
341623   Brooklyn  11237.0  7186284253             Spanish
341624      Bronx  10472.0  7183284523      Latin American
341625   Brooklyn  11217.0  7188584218              Donuts

[321411 rows x 8 columns]